language: node_js
sudo: false
node_js:
- '0.12'
branches:
  only:
  - master

install:
- npm install -g karma
- npm install
- npm run build

after_script: 
- process.exit()

cache:
  directories:
  - "$HOME/.nvm"