language: node_js
sudo: false
node_js:
- '0.12'
branches:
  only:
  - master
  - /^greenkeeper/.*$/

install:
- npm install -g karma
- npm install

after_script: 
- process.exit()

cache:
  directories:
  - "$HOME/.nvm"